SELECT A.TITLE, A.BOARD_ID, B.REPLY_ID, B.WRITER_ID, B.CONTENTS, DATE_FORMAT(B.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE -- 댓글 작성일 출력
FROM USED_GOODS_BOARD AS A
JOIN USED_GOODS_REPLY AS B ON A.BOARD_ID = B.BOARD_ID
WHERE A.CREATED_DATE BETWEEN '2022-10-00' AND '2022-10-31' -- 게시글 작성일이 2022년 10월
ORDER BY B.CREATED_DATE ASC, A.TITLE ASC -- 댓글 작성일 정렬